# File: cloudbuild.yaml
steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/api-unmaze',
        '-f',
        'Dockerfile.prd',
        '.',
      ]
    # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/api-unmaze']
    # deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'api-unmaze',
        '--async',
        '--image',
        'gcr.io/$PROJECT_ID/api-unmaze',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--max-instances',
        '1',
      ]

options:
  logging: CLOUD_LOGGING_ONLY
