version: '3'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - "db"
  db:
    image: 'postgres:15.1-alpine'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=teamway-test-work-planning-service
      - POSTGRES_PASSWORD=teamway-test-work-planning-service
      - POSTGRES_DB=teamway-test-work-planning-service

volumes:
  postgres_data:
    driver: local
